export const registerRootRoutes = (app) => {
  app.get("/", (req, res) => {
    res.json({
      name: "KainWise / NutriMind API",
      message: "AI food and wellness companion backend",
      endpoints: [
        "POST /api/v1/ai/analyze",
        "POST /api/v1/profiles",
        "POST /api/v1/auth/register",
        "POST /api/v1/auth/login",
        "POST /api/v1/auth/refresh",
        "POST /api/v1/auth/password-reset/request",
        "POST /api/v1/auth/password-reset/confirm",
        "GET /api/v1/auth/me",
        "POST /api/v1/profiles/:profileId/invites",
        "POST /api/v1/profiles/invites/accept",
        "GET /api/v1/profiles/:profileId/relations",
        "POST /api/v1/health-context",
        "POST /api/v1/scans",
        "POST /api/v1/scans/image",
        "POST /api/v1/scans/upload",
        "POST /api/v1/meals",
        "POST /api/v1/meals/photo",
        "GET /api/v1/tasks/:profileId",
        "POST /api/v1/tasks",
        "POST /api/v1/tasks/:profileId/generate",
        "POST /api/v1/water",
        "GET /api/v1/water/:profileId",
        "PATCH /api/v1/water-logs/:logId",
        "DELETE /api/v1/water-logs/:logId",
        "POST /api/v1/sleep",
        "GET /api/v1/sleep/:profileId",
        "PATCH /api/v1/sleep-logs/:logId",
        "DELETE /api/v1/sleep-logs/:logId",
        "GET /api/v1/budget/:profileId",
        "GET /api/v1/budget-logs/:profileId",
        "POST /api/v1/budget-logs",
        "DELETE /api/v1/budget-logs/:logId",
        "GET /api/v1/grocery-list/:profileId",
        "GET /api/v1/fitness/exercises",
        "GET /api/v1/fitness/muscles",
        "GET /api/v1/fitness/equipment",
        "GET /api/v1/fitness/workout/:profileId",
        "POST /api/v1/fitness/workout/:profileId/suggest",
        "GET /api/v1/fitness/workouts/:profileId",
        "POST /api/v1/fitness/workouts",
        "GET /api/v1/rewards/:profileId",
        "GET /api/v1/wellness/:profileId",
        "GET /api/v1/safety",
        "POST /api/v1/gemini-token",
        "GET /api/v1/health",
        "POST /api/v1/diary",
        "GET /api/v1/security/csrf",
        "GET /api/v1/dashboard/:profileId",
        "GET /api/v1/calendar/:profileId",
        "GET /api/v1/insights/:profileId",
        "GET /api/v1/scanner-context/:profileId",
        "GET /api/v1",
      ],
    });
  });
};
